sonar.projectKey=QWED-AI_qwed-finance
sonar.organization=qwed-ai

sonar.projectName=qwed-finance
sonar.projectVersion=2.0.0

# Source
sonar.sources=qwed_finance
sonar.tests=tests
sonar.python.version=3.11

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/tests/**,**/examples/**
